# Generated by Django 6.0.2 on 2026-05-27 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notificationchannel_notificationrule_notificationlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAIRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('fund', '基金分析'), ('position', '持仓分析')], max_length=20)),
                ('schedule_time', models.TimeField(help_text='每日触发时间')),
                ('trading_day_only', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_ai_rules', to='api.account')),
                ('channels', models.ManyToManyField(related_name='scheduled_ai_rules', to='api.notificationchannel')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_ai_rules', to='api.fund')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_ai_rules', to='api.aiprompttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_ai_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '定时 AI 规则',
                'verbose_name_plural': '定时 AI 规则',
                'db_table': 'scheduled_ai_rule',
            },
        ),
        migrations.CreateModel(
            name='ScheduledAIRuleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run_date', models.DateField(db_index=True)),
                ('analysis_target_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_ai_logs', to='api.notificationchannel')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.scheduledairule')),
            ],
            options={
                'verbose_name': '定时 AI 规则执行日志',
                'verbose_name_plural': '定时 AI 规则执行日志',
                'db_table': 'scheduled_ai_rule_log',
            },
        ),
        migrations.AddIndex(
            model_name='scheduledairule',
            index=models.Index(fields=['user', 'is_active'], name='scheduled_a_user_id_55b4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledairule',
            index=models.Index(fields=['schedule_time'], name='scheduled_a_schedul_fc4d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledairule',
            index=models.Index(fields=['target_type'], name='scheduled_a_target__752182_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledairule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', True), ('fund__isnull', False), ('target_type', 'fund')), models.Q(('account__isnull', False), ('fund__isnull', True), ('target_type', 'position')), _connector='OR'), name='scheduled_ai_rule_target_match', violation_error_message='定时 AI 规则的分析对象与类型必须匹配'),
        ),
        migrations.AddIndex(
            model_name='scheduledairulelog',
            index=models.Index(fields=['rule', 'run_date'], name='scheduled_a_rule_id_35d40c_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledairulelog',
            index=models.Index(fields=['rule', 'trigger_time'], name='scheduled_a_rule_id_957dea_idx'),
        ),
    ]
